#!/bin/bash
# Ensure .env exists in the project root, and thus we load it
if [ ! -f ".env" ]; then
    echo "Error: .env is missing in the project root. Please create it and add the required secrets, including DATABASE_URL."
    exit 1
fi
set -o allexport
source .env
set +o allexport

# Exit immediately if a command exits with a non-zero status.
set -e

echo "All Docker volumes shall be killed!"
read -r -p "Are you sure you want to proceed? (y/N) " response
response=${response,,} # tolower

if [[ "$response" =~ ^(yes|y)$ ]]; then
    docker compose down --volumes
else
  echo "Operation cancelled by user."
  exit 1
fi

#docker compose build --no-cache
helper/bash/start --no-cache
