#!/bin/bash

echo "This script will help you apply the single-layer nginx configuration."
echo ""
echo "Please run these commands on the server as admin user:"
echo ""
echo "1. Apply new nginx configuration:"
echo "   sudo cp /home/admin/nginx-single-layer.conf /etc/nginx/sites-available/mylayer.org"
echo ""
echo "2. Test nginx configuration:"
echo "   sudo nginx -t"
echo ""
echo "3. If test passes, reload nginx:"
echo "   sudo systemctl reload nginx"
echo ""
echo "4. Stop the frontend container:"
echo "   docker stop mylayer_pessoa_frontend"
echo ""
echo "5. Update docker-compose to remove frontend service:"
echo "   cd /home/admin/app"
echo "   # Edit docker-compose.mylayer.yml and comment out or remove the frontend service"
echo ""
echo "The single-layer nginx is now serving static files directly from:"
echo "/home/admin/app/frontend-build/"
echo ""
echo "Benefits:"
echo "- One less nginx layer (reduced complexity)"
echo "- WebSocket goes through only one proxy"
echo "- Easier to debug and maintain"